### ISSUE TITLE
Minor fix

### ISSUE THREAD

**Issue by csprsmt** [ArtLeav/SDXL-cropper#1]
`Traceback (most recent call last):
  File "C:\Users\amdf01\Documents\SDXL-cropper-main\Cropper.py", line 40, in <module>
    new_img.save(os.path.join(dst_dir, new_filename), quality=quality_val)
  File "C:\Python31011\lib\site-packages\PIL\Image.py", line 2436, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: ...`

Fix by putting a + instead of , at line 40:
new_img.save(os.path.join(dst_dir + new_filename), quality=quality_val)

**Comment by csprsmt** [comment]
hm now its not outputting to the folder.
Not sure what is up

**Comment by AronWick** [comment]
![image](https://github.com/ArtLeav/SDXL-cropper/assets/162827590/ececa1ee-ff11-4e83-b74b-d341093991f5)

**Comment by csprsmt** [comment]
My bad. 
Don't know why it is working now, but it does..
